/**
 * Actor — execute concrete actions (tool calls, content generation).
 *
 * For "respond" action: extracts the LLM-generated response from context.reasoning.
 * For other actions: stub implementation (tool calling added in M3).
 */
import type { LanguageModel } from "ai";
import { getLogger } from "../infra/logger.ts";
import type { Persona } from "../identity/persona.ts";
import type { TaskContext, PlanStep, ActionResult } from "../task/context.ts";

const logger = getLogger("cognitive.act");

export class Actor {
  // Reserved for M3: tool calling via LLM
  readonly model: LanguageModel;
  readonly persona: Persona;

  constructor(model: LanguageModel, persona: Persona) {
    this.model = model;
    this.persona = persona;
  }

  async run(context: TaskContext, step: PlanStep): Promise<ActionResult> {
    logger.info({ stepIndex: step.index, actionType: step.actionType }, "act_step_start");

    const startedAt = Date.now();

    let resultValue: unknown;

    if (step.actionType === "respond") {
      // Extract the response generated by the Thinker
      resultValue = (context.reasoning?.["response"] as string) ?? "";
    } else {
      // Generic stub for non-conversation actions
      resultValue = `[Stub] Completed step ${step.index}: ${step.description}`;
    }

    const result: ActionResult = {
      stepIndex: step.index,
      actionType: step.actionType,
      actionInput: step.actionParams,
      result: resultValue,
      success: true,
      startedAt,
      completedAt: Date.now(),
    };

    logger.info({ stepIndex: step.index, success: result.success }, "act_step_done");
    return result;
  }
}
