/**
 * Planner — decompose task into executable steps.
 *
 * For conversation tasks: generates a single "respond" step (no LLM call needed).
 * Complex multi-step planning will be added in M4.
 */
import type { LanguageModel } from "ai";
import { getLogger } from "../infra/logger.ts";
import type { Persona } from "../identity/persona.ts";
import type { TaskContext } from "../task/context.ts";
import type { Plan } from "../task/context.ts";

const logger = getLogger("cognitive.plan");

export class Planner {
  // Reserved for M4: LLM-powered planning
  readonly model: LanguageModel;
  readonly persona: Persona;

  constructor(model: LanguageModel, persona: Persona) {
    this.model = model;
    this.persona = persona;
  }

  async run(context: TaskContext): Promise<Plan> {
    logger.info("plan_start");

    const taskType = (context.perception?.["taskType"] as string) ?? "conversation";

    let plan: Plan;

    if (taskType === "conversation") {
      // Conversation: single step — deliver the response generated by Think
      plan = {
        goal: "Respond to the user",
        reasoning: "Conversation task: deliver the LLM-generated response",
        steps: [
          {
            index: 0,
            description: "Deliver response to user",
            actionType: "respond",
            actionParams: {},
            completed: false,
          },
        ],
      };
    } else {
      // Non-conversation: generic single-step plan (M4 will add LLM-powered planning)
      plan = {
        goal: context.inputText,
        reasoning: `Task type "${taskType}": single-step plan`,
        steps: [
          {
            index: 0,
            description: `Process task: ${context.inputText}`,
            actionType: "generate",
            actionParams: { prompt: context.inputText },
            completed: false,
          },
        ],
      };
    }

    logger.info({ stepsCount: plan.steps.length, taskType }, "plan_done");
    return plan;
  }
}
